---
- name: "get GPDB source"
  git:
    repo: 'https://github.com/greenplum-db/gpdb.git'
    dest: ~/workspace/gpdb
  register: gpdb_source

- name: "make GPDB 6 install dir"
  file:
    path: /6/
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: yes

- name: "configure GPDB"
  command: "./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/6/"
  args:
    chdir: ~/workspace/gpdb/
  when: gpdb_source is changed
  register: gpdb_configure

# TODO: I wan't to be able to build, but I don't know if its necessary
