---
# TODO - compile this when we start using packer - this takes ~ 1hour
# yum install wget gcc-c++ gmp-devel mpfr-devel libmpc-devel make
#
# cd ~/
# wget https://ftp.gnu.org/gnu/gcc/gcc-6.2.0/gcc-6.2.0.tar.gz
# tar xzvf gcc-6.2.0.tar.gz
# mkdir build-gcc-6.2.0
# cd build-gcc-6.2.0
# ../gcc-6.2.0/configure --prefix=/opt/gcc-6.2.0/ --enable-languages=c,c++,fortran,go --disable-multilib
# make -j7
# sudo make install
# The shortcut is to use the one we built and bake into images
# s3://toolchain-snowflakes/gcc-6.2.0-rhel7_x86_64.tar.gz
# untar in /opt/
# source /opt/gcc_env.sh

- name: put gcc snowflake into /opt/
  unarchive:
    # TODO: make getting this not manual
    src: ~/Downloads/gcc-6.2.0-rhel7_x86_64.tar.gz
    dest: /opt/
  become: yes

- name: source the provided file so that we use gcc-6.2.0
  lineinfile:
    path: ~/.bash_profile
    line: "source /opt/gcc_env.sh"
